# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Designer/B_Clientes.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_B_Clientes(object):
    def setupUi(self, B_Clientes):
        B_Clientes.setObjectName("B_Clientes")
        B_Clientes.resize(657, 304)
        B_Clientes.setMinimumSize(QtCore.QSize(657, 304))
        B_Clientes.setMaximumSize(QtCore.QSize(657, 304))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Ui_Designer\\Iconos/Icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        B_Clientes.setWindowIcon(icon)
        self.Line_Cliente = QtWidgets.QLineEdit(B_Clientes)
        self.Line_Cliente.setGeometry(QtCore.QRect(80, 10, 151, 20))
        self.Line_Cliente.setObjectName("Line_Cliente")
        self.B_Buscar = QtWidgets.QPushButton(B_Clientes)
        self.B_Buscar.setGeometry(QtCore.QRect(250, 9, 75, 23))
        self.B_Buscar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.B_Buscar.setAutoDefault(True)
        self.B_Buscar.setObjectName("B_Buscar")
        self.L_Cliente = QtWidgets.QLabel(B_Clientes)
        self.L_Cliente.setGeometry(QtCore.QRect(20, 10, 60, 16))
        self.L_Cliente.setObjectName("L_Cliente")
        self.Tabla_Clientes = QtWidgets.QTableWidget(B_Clientes)
        self.Tabla_Clientes.setGeometry(QtCore.QRect(10, 40, 621, 221))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Tabla_Clientes.setFont(font)
        self.Tabla_Clientes.setToolTip("")
        self.Tabla_Clientes.setStatusTip("")
        self.Tabla_Clientes.setAccessibleName("")
        self.Tabla_Clientes.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.Tabla_Clientes.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.Tabla_Clientes.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.Tabla_Clientes.setColumnCount(0)
        self.Tabla_Clientes.setObjectName("Tabla_Clientes")
        self.Tabla_Clientes.setRowCount(0)
        self.Tabla_Clientes.horizontalHeader().setVisible(True)
        self.Tabla_Clientes.horizontalHeader().setDefaultSectionSize(200)
        self.Tabla_Clientes.verticalHeader().setVisible(False)
        self.B_Canc = QtWidgets.QPushButton(B_Clientes)
        self.B_Canc.setGeometry(QtCore.QRect(550, 270, 75, 23))
        self.B_Canc.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.B_Canc.setAutoDefault(True)
        self.B_Canc.setObjectName("B_Canc")
        self.layoutWidget = QtWidgets.QWidget(B_Clientes)
        self.layoutWidget.setGeometry(QtCore.QRect(348, 12, 189, 19))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.R_Razon = QtWidgets.QRadioButton(self.layoutWidget)
        self.R_Razon.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.R_Razon.setChecked(True)
        self.R_Razon.setObjectName("R_Razon")
        self.horizontalLayout.addWidget(self.R_Razon)
        self.R_Alias = QtWidgets.QRadioButton(self.layoutWidget)
        self.R_Alias.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.R_Alias.setObjectName("R_Alias")
        self.horizontalLayout.addWidget(self.R_Alias)
        self.R_Cuit = QtWidgets.QRadioButton(self.layoutWidget)
        self.R_Cuit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.R_Cuit.setObjectName("R_Cuit")
        self.horizontalLayout.addWidget(self.R_Cuit)

        self.retranslateUi(B_Clientes)
        self.Line_Cliente.textChanged['QString'].connect(B_Clientes.QueryClientes) # type: ignore
        self.B_Canc.clicked.connect(B_Clientes.Cerrar) # type: ignore
        self.Tabla_Clientes.cellDoubleClicked['int','int'].connect(B_Clientes.Resultados) # type: ignore
        self.B_Buscar.clicked.connect(B_Clientes.QueryClientes) # type: ignore
        self.R_Razon.clicked.connect(B_Clientes.setFocus) # type: ignore
        self.R_Alias.clicked.connect(B_Clientes.setFocus) # type: ignore
        self.R_Cuit.clicked.connect(B_Clientes.setFocus) # type: ignore
        self.Tabla_Clientes.cellPressed['int','int'].connect(B_Clientes.Resultados) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(B_Clientes)
        B_Clientes.setTabOrder(self.Line_Cliente, self.Tabla_Clientes)
        B_Clientes.setTabOrder(self.Tabla_Clientes, self.B_Buscar)
        B_Clientes.setTabOrder(self.B_Buscar, self.B_Canc)

    def retranslateUi(self, B_Clientes):
        _translate = QtCore.QCoreApplication.translate
        B_Clientes.setWindowTitle(_translate("B_Clientes", "Busqueda de Clientes"))
        self.B_Buscar.setText(_translate("B_Clientes", "Buscar"))
        self.L_Cliente.setText(_translate("B_Clientes", "Cliente"))
        self.B_Canc.setText(_translate("B_Clientes", "Cancelar"))
        self.B_Canc.setShortcut(_translate("B_Clientes", "Esc"))
        self.R_Razon.setText(_translate("B_Clientes", "Razon Social"))
        self.R_Alias.setText(_translate("B_Clientes", "Alias"))
        self.R_Cuit.setText(_translate("B_Clientes", "CUIT"))
