# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Designer/B_Productos.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_B_Productos(object):
    def setupUi(self, B_Productos):
        B_Productos.setObjectName("B_Productos")
        B_Productos.resize(494, 304)
        B_Productos.setMinimumSize(QtCore.QSize(494, 304))
        B_Productos.setMaximumSize(QtCore.QSize(494, 304))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Ui_Designer\\Iconos/Icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        B_Productos.setWindowIcon(icon)
        self.B_Buscar = QtWidgets.QPushButton(B_Productos)
        self.B_Buscar.setGeometry(QtCore.QRect(250, 9, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setBold(True)
        font.setWeight(75)
        self.B_Buscar.setFont(font)
        self.B_Buscar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.B_Buscar.setObjectName("B_Buscar")
        self.Tabla_Productos = QtWidgets.QTableWidget(B_Productos)
        self.Tabla_Productos.setGeometry(QtCore.QRect(10, 40, 471, 221))
        self.Tabla_Productos.setToolTip("")
        self.Tabla_Productos.setStatusTip("")
        self.Tabla_Productos.setAccessibleName("")
        self.Tabla_Productos.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.Tabla_Productos.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.Tabla_Productos.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.Tabla_Productos.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.Tabla_Productos.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.Tabla_Productos.setColumnCount(0)
        self.Tabla_Productos.setObjectName("Tabla_Productos")
        self.Tabla_Productos.setRowCount(0)
        self.Tabla_Productos.horizontalHeader().setVisible(True)
        self.Tabla_Productos.horizontalHeader().setDefaultSectionSize(200)
        self.Tabla_Productos.verticalHeader().setVisible(False)
        self.B_Canc = QtWidgets.QPushButton(B_Productos)
        self.B_Canc.setGeometry(QtCore.QRect(390, 269, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setBold(True)
        font.setWeight(75)
        self.B_Canc.setFont(font)
        self.B_Canc.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.B_Canc.setObjectName("B_Canc")
        self.layoutWidget = QtWidgets.QWidget(B_Productos)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 220, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.L_Cliente = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setBold(True)
        font.setWeight(75)
        self.L_Cliente.setFont(font)
        self.L_Cliente.setObjectName("L_Cliente")
        self.horizontalLayout.addWidget(self.L_Cliente)
        self.Line_Producto = QtWidgets.QLineEdit(self.layoutWidget)
        self.Line_Producto.setObjectName("Line_Producto")
        self.horizontalLayout.addWidget(self.Line_Producto)

        self.retranslateUi(B_Productos)
        self.B_Buscar.clicked.connect(B_Productos.QueryProductos) # type: ignore
        self.Line_Producto.returnPressed.connect(B_Productos.QueryProductos) # type: ignore
        self.Tabla_Productos.cellDoubleClicked['int','int'].connect(B_Productos.Resultados) # type: ignore
        self.B_Canc.clicked.connect(B_Productos.Cerrar) # type: ignore
        self.Line_Producto.textChanged['QString'].connect(B_Productos.QueryProductos) # type: ignore
        self.Tabla_Productos.cellPressed['int','int'].connect(B_Productos.Resultados) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(B_Productos)

    def retranslateUi(self, B_Productos):
        _translate = QtCore.QCoreApplication.translate
        B_Productos.setWindowTitle(_translate("B_Productos", "Busqueda de Productos"))
        self.B_Buscar.setText(_translate("B_Productos", "Buscar"))
        self.B_Canc.setText(_translate("B_Productos", "Cancelar"))
        self.B_Canc.setShortcut(_translate("B_Productos", "Esc"))
        self.L_Cliente.setText(_translate("B_Productos", "Productos"))
