# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Designer/Precios.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Precios(object):
    def setupUi(self, Precios):
        Precios.setObjectName("Precios")
        Precios.resize(480, 520)
        Precios.setMinimumSize(QtCore.QSize(480, 520))
        Precios.setMaximumSize(QtCore.QSize(480, 520))
        Precios.setFocusPolicy(QtCore.Qt.NoFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Ui_Designer\\Iconos/Icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Precios.setWindowIcon(icon)
        self.frame = QtWidgets.QFrame(Precios)
        self.frame.setGeometry(QtCore.QRect(10, 10, 462, 50))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.splitter_2 = QtWidgets.QSplitter(self.frame)
        self.splitter_2.setGeometry(QtCore.QRect(313, 13, 140, 23))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.B_Buscar = QtWidgets.QPushButton(self.splitter_2)
        self.B_Buscar.setObjectName("B_Buscar")
        self.B_Salir = QtWidgets.QPushButton(self.splitter_2)
        self.B_Salir.setObjectName("B_Salir")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(9, 16, 26, 16))
        self.label.setObjectName("label")
        self.C_Lista = QtWidgets.QComboBox(self.frame)
        self.C_Lista.setGeometry(QtCore.QRect(41, 15, 126, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.C_Lista.setFont(font)
        self.C_Lista.setObjectName("C_Lista")
        self.splitter = QtWidgets.QSplitter(self.frame)
        self.splitter.setGeometry(QtCore.QRect(172, 16, 135, 17))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.R_Negocio = QtWidgets.QRadioButton(self.splitter)
        self.R_Negocio.setChecked(True)
        self.R_Negocio.setObjectName("R_Negocio")
        self.R_Camio = QtWidgets.QRadioButton(self.splitter)
        self.R_Camio.setObjectName("R_Camio")
        self.frame_2 = QtWidgets.QFrame(Precios)
        self.frame_2.setGeometry(QtCore.QRect(10, 70, 461, 442))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.T_Lista = QtWidgets.QTableWidget(self.frame_2)
        self.T_Lista.setGeometry(QtCore.QRect(30, 34, 389, 377))
        self.T_Lista.setObjectName("T_Lista")
        self.T_Lista.setColumnCount(0)
        self.T_Lista.setRowCount(0)
        self.T_Lista.verticalHeader().setVisible(False)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(42, 416, 370, 13))
        self.label_2.setObjectName("label_2")
        self.Line_B = QtWidgets.QLineEdit(self.frame_2)
        self.Line_B.setGeometry(QtCore.QRect(40, 6, 370, 20))
        self.Line_B.setObjectName("Line_B")

        self.retranslateUi(Precios)
        self.B_Buscar.clicked.connect(Precios.Buscar) # type: ignore
        self.T_Lista.itemChanged['QTableWidgetItem*'].connect(Precios.SavePrecio) # type: ignore
        self.Line_B.textChanged['QString'].connect(Precios.Search) # type: ignore
        self.B_Salir.clicked.connect(Precios.Salir) # type: ignore
        self.T_Lista.itemClicked['QTableWidgetItem*'].connect(Precios.SetValor) # type: ignore
        self.R_Negocio.clicked.connect(Precios.SetLista) # type: ignore
        self.R_Camio.clicked.connect(Precios.SetLista) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Precios)

    def retranslateUi(self, Precios):
        _translate = QtCore.QCoreApplication.translate
        Precios.setWindowTitle(_translate("Precios", "Precios"))
        self.B_Buscar.setText(_translate("Precios", "Buscar"))
        self.B_Salir.setText(_translate("Precios", "Salir"))
        self.label.setText(_translate("Precios", "Lista:"))
        self.R_Negocio.setText(_translate("Precios", "Negocio"))
        self.R_Camio.setText(_translate("Precios", "Camioneta"))
        self.label_2.setText(_translate("Precios", "Doble-click en el precio que desea modificar. Los precios deben ser CON IVA"))
        self.Line_B.setPlaceholderText(_translate("Precios", "Buscar..."))
