# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Designer/Zonas.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Zonas(object):
    def setupUi(self, Zonas):
        Zonas.setObjectName("Zonas")
        Zonas.resize(262, 146)
        Zonas.setMinimumSize(QtCore.QSize(262, 146))
        Zonas.setMaximumSize(QtCore.QSize(262, 146))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Ui_Designer\\Iconos/Icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Zonas.setWindowIcon(icon)
        self.frame = QtWidgets.QFrame(Zonas)
        self.frame.setGeometry(QtCore.QRect(10, 20, 231, 75))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.L_Coment = QtWidgets.QLabel(self.frame)
        self.L_Coment.setGeometry(QtCore.QRect(28, 79, 170, 20))
        self.L_Coment.setStyleSheet("color: rgb(0, 85, 0);")
        self.L_Coment.setText("")
        self.L_Coment.setAlignment(QtCore.Qt.AlignCenter)
        self.L_Coment.setObjectName("L_Coment")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 12, 188, 48))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.Box_Prov = QtWidgets.QComboBox(self.layoutWidget)
        self.Box_Prov.setObjectName("Box_Prov")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Box_Prov)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.Line_Dgr = QtWidgets.QLineEdit(self.layoutWidget)
        self.Line_Dgr.setObjectName("Line_Dgr")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.Line_Dgr)
        self.splitter_2 = QtWidgets.QSplitter(Zonas)
        self.splitter_2.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter = QtWidgets.QSplitter(Zonas)
        self.splitter.setGeometry(QtCore.QRect(31, 106, 190, 23))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.B_Mod = QtWidgets.QPushButton(self.splitter)
        self.B_Mod.setObjectName("B_Mod")
        self.B_Salir = QtWidgets.QPushButton(self.splitter)
        self.B_Salir.setObjectName("B_Salir")

        self.retranslateUi(Zonas)
        self.Box_Prov.currentIndexChanged['int'].connect(Zonas.showDGR) # type: ignore
        self.B_Mod.clicked.connect(Zonas.Mod) # type: ignore
        self.B_Salir.clicked.connect(Zonas.Cerrar) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Zonas)

    def retranslateUi(self, Zonas):
        _translate = QtCore.QCoreApplication.translate
        Zonas.setWindowTitle(_translate("Zonas", "Zonas"))
        self.label.setText(_translate("Zonas", "Provincia:"))
        self.label_2.setText(_translate("Zonas", "D.G.R %"))
        self.B_Mod.setText(_translate("Zonas", "Modificar"))
        self.B_Salir.setText(_translate("Zonas", "Salir"))
